### ISSUE TITLE
Your App has been pirated by lubieapki

### ISSUE THREAD

**Issue by PhilippMatthes** [jacobpedd/Wishlist-Plus#3]
Hello!

My Apps were pirated by Github user [lubieapki](https://github.com/lubieapki) and published on codecanyon, where they were copied by someone and published in the iOS App Store. Your App may be affected as well:

https://itunes.apple.com/app/id1294411080

Please report lubieapki at Github and contact Apple to remove the pirated app.

Sincerely
Philipp Matthes

**Comment by jacobpedd** [comment]
Thank you for letting me know about this!

**Comment by PhilippMatthes** [comment]
No problem dude 👍🏻 I know it's very annoying, hope you have a nice day anyways 👌🏻
